[package]
name = "human_os"
version = "0.1.4"
edition = "2024"

[dependencies]
once_cell = "1.21.3"
rdev = "0.4.6"
x11rb = "0.13.2"

[profile.release]
opt-level = "z"        # optimize for size (or "s")
lto = true             # link-time optimization
codegen-units = 1      # better optimization
strip = true           # strip symbols
panic = "abort"        # removes unwinding machinery
